### ISSUE TITLE
Decide between RSpec and Minitest

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1139]
Minitest benefits:

* is a gem that comes standard with a Ruby install
* closest to the x-unit style of testing that every other language has support for
* looks more like plain ruby, more approachable to newcomers
* for simple tests, takes less code to write

Minitest drawbacks:

* for pretty diffs you have to enable pretty diffs
* mocking by default is limited though you can use the external mocha ruby gem

RSpec benefits:

* includes mocking and pretty diffs by default
* can do some things out of the box with testing that are difficult to do in minitest

RSpec drawbacks:

* DSL, not plain ruby, can be verbose and scary to newcomers
* sometimes more verbose than minitest
* the nesting contexts can dry up tests but also make tests very difficult to read
* let + subject pattern can make tests very difficult to read
* slower than minitest

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823104551926) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Personally I find rspec semantics much easier to read and much more feature rich.

**Comment by johrstrom** [comment]
So I think we should prefer minitest over rspec just because it's simpler. However, we can't get rid of Rspec entirely because that's how we run e2e tests, so that'll keep.

So I'm going to close this as will do (kinda) and we'll open tickets specifically for different components should we choose to refactor them (like we're kinda doing with nginx_stage right now).
