### ISSUE TITLE
File editor - first class citizen? refactor? 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1141]
This is a discussion around our long term strategy for the file editor. I'd thought about making it a first class citizen. There are also some refactors out there. So this ticket is to discuss things to think about what our long term plan is for it.

I think things to keep in mind are how folks use it and how folks _want_ to use it. And of course our own maintenance costs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823149769595) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
As it matures, consider https://codemirror.net/6/ since it is accessibility focused.

Also, the editor code as it is exists as a bit of unorganized JavaScript code. If that JS is reorganized into a component, it could also be used via a modal for quick edits in other parts of the app, as long as that model had a link to "expand to the full window" which would take it to the files app - but needs to be thought through well because you don't want to type in changes and then expand the window and lose changes.

Minimally, reorganizing into a component with a toolbar would make the code base and easier to reason about and it is work that an intern may be able to tackle.

**Comment by ericfranz** [comment]
Also, this is a good project for an intern because it is a small "app" with a lot of room for improvement.

**Comment by msquee** [comment]
@johrstrom I've thought a lot about this specific area and have mockups for this:

https://user-images.githubusercontent.com/6081892/119893427-57962280-bf09-11eb-8194-4b56dd8f85dc.mov

This could easily be extracted as a Stimulus.js component or React component, I used React for this demo.

**Comment by johrstrom** [comment]
I can't tell now (a few years later) what this ticket was about. Maybe it was about the fact that the file editor used to be it's own app and now it's a part of the dashboard? Or maybe it's that the file editor's navigation bar was different than the rest of the dashboard (after we pulled it into the dashboard)?

But even so, now (in 4.0) the file editor is a part of the dashboard, and indeed does have the dashboard's navigation bar as well.

So I'm going to close this as it's either done, or we've lost the thread on it altogether and don't know what sort of resolution I was thinking of.
