### ISSUE TITLE
future of subapps 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1142]
It's become apparent that subapps are not so great to the internals of our code base. This issue is to talk about what's next for that whole concept.

I guess a good problem statement for them was - how can we use template code so that folks can get 80% of the functionality and reconfigure the other 20%.

So how can we provide that same functionality in a cleaner way. Can we keep backward compatibility? I wonder if there's a way to.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823208502400) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
In the existing code, isolate the knowledge of subapps to the SysRouter and other router classes, and in particular isolate the knowledge to the factory method that instantiates app objects, in SysRouter's case, `SysRouter.apps`. So `SysRouter.apps` becomes a lot more complex. But then FeaturedApp, Router, TokenMatcher, and BatchConnect::App don't have any concept of a subapp. How this works is that `SysRouter.apps` makes the determination that an app has "subapps" and creates a separate app object for each "subapp" and also creates a separate app for the "superapp" if that is a valid app by itself as well.

After this is done then https://github.com/OSC/ondemand/issues/210 can be done, and to determine whether or not the "superapp" should be included, instead of calling valid? to render the erb, we would check if it is marked as "abstract" in the manifest - intending to not be treated as an app itself.

**Comment by ericfranz** [comment]
As for "what's next for that whole concept". Several ideas.

A. A batch connect app specifies a template in the manifest OR in the form.yml that it uses. That template is a name of a directory somewhere in /etc/. So custom desktops become directories under /sys but can still reuse a lot of the same code.


B. Build a better plugin architecture. Start by gathering example job scripts that are generated from different interactive apps, and then maybe also compare these generated scripts/work directories to some of the scripts/work directories of apps like weld predictor, VFT, other workflow-style apps that used machete and machete_rails (see code.osu.edu - I believe there was an old openfoam app, and in GitHub there is a batch sim app that Rutgers actually built off of - see what they did to). Can you imagine another way to generate these scripts (even if you combine them) that, for instance, doesn't use a framework approach, but a library approach? Something that makes it more explicit to an administrator what is happening? For example, in the batch connect code in ood_core, there are alot of variables you can change and those end up changing values in the job script that is rendered. What if, instead, the job script code was arranged as a bunch of bash functions, and a custom job script is just calling those with arguments, and the variations that you could specify 



C. Regardless of what you do above, get rid of "SmartAttributes". Move scheduler specific information into ood_core. "SmartAttributes" where there is a server and client code to a single attribute, might be replaced by being able to specify actual scheduler arguments in the web form itself as values and then handling logic client side. We would of course want to support validation of the forms.

**Comment by johrstrom** [comment]
I'm going to close this as it's not clear after all these years what we should do. Subapps do indeed work, so there's that. and this seems to be all about the internals of the code base so it wouldn't affect users anyhow.
