### ISSUE TITLE
port to some js component libraries

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1162]
There's been a lot of hubbub about libraries like react, preact, vue and countless others. We use alot of jquery + fetch, so the question is, should me move some (or all) javascript to these component libraries.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823112199407) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
A "javascript component" is usually a `<div>` identified by a class or id that, using some extra JavaScript (or by convention of the class name, id name, or data attribute), results in the div's content being managed by JavaScript code that is encapsulated in a reusable library. This is conceptually how Bootstrap tooltips work, how jQuery [Datatables](https://datatables.net/) works, and how React and Vue components work. When we write "spaghetti javascript" inside a <script> tag and utilize Handlebars in the process, we are also following this pattern - it is just that the boundaries of a specific component's code may not be easily identified and the code not easily reusable.

The end goal of adopting React/Preact+htm for some components in OnDemand is to:

1. set clear boundaries around the code for different "components" in our application
2. make those components reusable in other contexts; so for example, the file navigation/manger component could be reused as a file picker component or used as the base for a custom application
3. remove some boilerplate code; lots of libraries like Stimulus or React or Vue provide some simple abstractions around the plumbing of connecting a block of code to an event handler which both reduces the number of lines of code for a given component and makes it easier to reason about

I think one of the points I'd like to make is that you can set clear boundaries and make "components reusable" while using plain JavaScript or JavaScript+jQuery. It just takes more discipline and requires you to adopt some patterns that might be similar to what structure is imposed on you by a library like React.

Beyond what we are using right now, I think the best choice is to use React/Preact+htm ([htm](https://github.com/developit/htm) works on the front end without a custom compiler), optionally using JSX on the backend for core components if/when it provides benefit over htm.

Why React over others? It is more widely used and other projects/groups that we have burgeoning collaborations with use React.

Why htm instead of JSX? Because it is plain JavaScript, so it works without a compilation step, meaning it can be added at runtime in custom widgets or in interactive app enhancements or in other places.

I think as a utility library when you don't need do to custom view rendering, I think you should also experiment with Stimulus, because the point of that is just to remove some boilerplate and help you reason about it. Also, it may be a good fit for some of the dynamic enhancements we might want to provide as a default to batch connect apps.

- A small component that would benefit from React (or similar) would be the transfer status widget for the files app.
- The subset of functionality we require that we are currently using datatables for could probably be provided by a custom React component or an extension of an existing react datatables component that would let us better customize the views for different screen sizes

**Comment by ericfranz** [comment]
To clarify, "jquery + fetch" vs "react" is not a proper comparison. It's more like "jquery event handling boilerplate + handlebars that's not a composable component easily developed in isolation" vs "react". In both cases you still need to make the decision of whether to use
Xmlhttprequest or fetch or jquery wrapper around xmlhttprequest or axios when doing requests. In fact you can use jquery and react together in this regard. React is just for rendering views or parts of views in a structured and composable way that promotes code reuse and removes some boilerplate to connect click events with functions.

The basic functionality of the base library is also tiny - so if you stick with the basics it takes a small time investment learn.

Stimulus doesn't do views: it just manages the click event binding (and target dom element selection) in a structured way. Instead of a bunch of separate html classes/ids and a bunch of separate jquery $() selections you have structured group of functions in one or more stimulus controllers with a set of classes/ids that follow a naming convention. And then you don't have to worry about the timing for when jquery calls to bind to these elements, or rebind after new dom elements are fetched. 

You could still use jquery inside of a stimulus controller. It is a really small library.

In both cases trying them out on a small component/area of the dashboard app will be low cost potentially high reward investment.

**Comment by ericfranz** [comment]
One final thought on this matter. In interviews and blog articles with DHH on the topic, he identified two classes of client side JavaScript:

1. JavaScript Sprinkles: small blocks of JS meant to insert some dynamic update or functionality to html rendered server side (fetch an update for a small portion of the site)
2. JavaScript components: a custom calendar widget or datatable 

Stimulus.js was designed to make JavaScript sprinkles more maintainable 

React.js was designed to make JavaScript components more maintainable

Both can be used in very small or large portions of a page, and neither require the adoption of an SPA and both require minimal investment to learn the basics.

**Comment by johrstrom** [comment]
We are likely to go to Hotwire scheme with turbo + stimulus and plain old javascript. There's little to no reason to pick up large javascript frameworks like React at this time as it just spreads the team too thin in terms of what technologies they have to be familiar with.

> 1. JavaScript Sprinkles: small blocks of JS meant to insert some dynamic update or functionality to html rendered server side (fetch an update for a small portion of the site)
> 2.  JavaScript components: a custom calendar widget or datatable

I think the big thing here is that we don't actually want javascript components (number 2) and instead favor writing html partials in Rails and using option 1 and/or turbo to update pages.  So I'm going to close this as we're likely going to favor html partials + rails over more extensive javascript libraries.

**Comment by stdweird** [comment]
@johrstrom  @ericfranz  in light of https://www.cve.org/CVERecord?id=CVE-2025-55182 , can you confirm/clarify that react is not used by main ondemand components? (who knows what the possible apps use, but that is another story)

**Comment by johrstrom** [comment]
No we don't use react. Here's a list of our direct dependencies. You can find the `yarn.lock` for all the indirect dependencies.

shell: https://github.com/OSC/ondemand/blob/master/apps/shell/package.json
dashboard: https://github.com/OSC/ondemand/blob/master/apps/dashboard/package.json

**Comment by stdweird** [comment]
thanks for confirming!
