### ISSUE TITLE
Quick launch icons

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1175]
The team at Harvard has experimented with and perhaps deployed quick launch icons on the dashboard. Unlike pinned apps, these icons directly launch apps with some static settings so there's no need for a form.

This ticket is to (a) gauge interest and (b) any flesh out design work or additional requirements or features.

Note that this feature may rely on an API to actually create these jobs.

- [x] #1819
- [x] #1899
- [x] #1900
- [x] #1836
- [x] #1963

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737361127457) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment]
This is absolutely an important feature for the OnDemand project and fulfills part of the "WIMPy" desktop (https://en.wikipedia.org/wiki/WIMP_(computing)) vision of the proposal. Pinned apps that are quick launch buttons, for example.

The IQSS customized dashboard demo we saw used quick launch with the sessions displaying on the same page. In OnDemand I think we would want to reserve the ability for quick launch to just send you to the sessions page with new session created, though we could also have a custom quick launch widget that would display sessions and launch buttons inline.

Quick launch button feature should be expanded to support "partially applied functions": the most common use case at OSC is the account field. Everything else for an app might be pre-set, but the account field might be required by the user to input. When the user clicks the launch button, a form (either on a new page, or in a modal) displays to the user to specify the remaining unset input values, such as account. In other cases, this might be a list of options specified by the quick launch button configuration (a set of options more constricting than the default). A benefit of this approach is that for class.osc.edu, for example, we could just use the default jupyter app and use the quick launch buttons to enforce the restrictions and options, instead of creating a custom jupyter app for a class.

A "partially applied" quick launch buttons should be able to be configured to require the input be a file path to a file or directory and then be configured to appear in the context menu for a file or directory in the Files manager interface. For example, imagine a quick launch button that requires as an input the path to a jupyter notebook. If associated with the files app with all .ipynb files, "Open in Jupyter"  appears as an option. When you click that in the files app, the path to the notebook supplies the required argument to the "partially applied" quick launch button, and if the rest of the quick launch button input requirements are satsified, the job would simply launch. This feature would fulfill the proposal to associate files and apps side by side.

Eventually we want to add support for user customization of which apps appear in the pinned apps view. It would be nice to be able to chose quick launch buttons to add to the pinned apps widget, and to see a list of quick launch buttons along side their app's. 

Being able to fill out a web form on an interactive app and save that input as a new quick launch button (instead of submitting a job) would enable users to build custom quick launch buttons. Optionally, previously submitted interactive app sessions could be saved as a quick launch button.

Finally, there is the ideal of further streamlining app launching to bypass the sessions page altogether. Rather, a new window/tab is opened at `/sessions/show/39dcb8e0-187f-4e2f-bc5c-7e18518f7d1c` which would show the status of the job if the job were queued or starting, and would show or redirect to the NoVNC page or the JupyterNotebook proxy page. Basically the flow from the user's perspective would be:

<img src="https://user-images.githubusercontent.com/512333/119719477-ce162000-be36-11eb-8728-767643ae16bd.png" width="500">

**Comment by ericfranz** [comment]
Note: while this was marked as OOD2.1 the above is multiple features that should be broken out into separate issues and scheduled appropriately.

**Comment by ericfranz** [comment]
I forgot one thing related to that idea of adding quick lunch buttons to the files management interface: we will be extending the files management interface to support working with cloud storage like OneDrive and Box, Globus, and hopefully even Canvas in the future. The goal is that these integrations will be exposed to the rest of OnDemand through a common file manage interface that we build. And then a quick launch button that integrates with the file management interface could “open a jupyter notebook in jupyterlab” from a notebook in your home directory OR in a OneDrive account OR in a Canvas account directory etc. etc. The idea here ultimately is to provide similar launch capabilities like are provided by Google Colab but being able to extend that to all OnDemand interactive apps.

**Comment by ericfranz** [comment]
Here is a mockup of the quick launch button integrated with the files app:

<img width="1047" alt="jobs_open_in_app" src="https://user-images.githubusercontent.com/512333/119984898-f7968f00-bf8f-11eb-9859-15cc9724f4c4.png">

**Comment by rsettlage** [comment]
It seems to me a concept could be that when a user is on a generic app launch form, there could be a checkbox or something to "make quick launch", which then takes all the form values, creates the QL yml file and then displays the app QL button.  I could see where users might create more than one for a specific app.  I am thinking of two scenarios, one is a super quick start for making plots or something in R, another might be an R app for a specific project where the startup would get into the project folder and may even load a project file if appropriate, but may be different in the resource request from the quicker make a plot R.
Another thought, on the QL app page, I would have a column with running apps where the apps had the same button-y look rather than a page wide card, but had the connection and links on them.  I would make the column have two tabs, running and completed and have a scroll bar to allow more visible.  Maybe even 3 tabs, add one for failed.  OR, perhaps better, add a checkbox or something, ideally to the running app card, to allow users to "favorite" a job.  That could mean that job's settings become a QL or perhaps that job, once finished, is added to a fav jobs tab.  The idea is that either the job settings or the job results are somehow important.
10:27
I could see how this would integrate with 2.0.  The "favorite apps" we were thinking about is a bit more general, the quick launch is a nice way to make it even more of a shortcut to a specific repeating task

**Comment by johrstrom** [comment]
There's always more, but I think we're good with this feature as it is. At least, good enough to launch and solicit feedback.
