### ISSUE TITLE
Submit job from files app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1183]
The idea here is to be able to select a file that may be a bash script, and choose a "submit as batch job". 

![](https://user-images.githubusercontent.com/512333/120052876-8093e180-bff5-11eb-8c32-392740faaaa1.png)

This would bring up a web form with options similar to the Job Composer Job Options page to submit the job.

After submitting, it might show a message on the directory with a link to the Active Jobs page for showing your apps or the specific job if we added a "show page" for a specific job to Active Jobs => so you can link to a specific job.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823116308583) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We're thinking to close this because you lose context when you submit the job. Maybe the link is helpful, but now that you've created the job - where's the view to track it? I think the project manager solves this better than this feature because it has panels of running & completed jobs within that project.
