### ISSUE TITLE
make passenger_pool_idle_time configurable

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1208]
this ticket is to make `passenger_pool_idle_time` configurable for the PUNs as a request from TotalSim who'd like it extended to 10 minutes or so.

**Comment by treydock** [comment]
@johrstrom This will likely be a different issue, but since there are so many possible passenger related settings we don't support, I wonder if we should also add the ability for a site to add arbitrary passenger settings to the NGINX PUN configs?  I wasn't sure if that would be a good idea or open people up to shooting themselves in the foot.

**Comment by johrstrom** [comment]
Yea let's open that ticket and discuss there. It's a bit advanced, so I'd guess someone who uses it may know what they're doing? In any case, I think we could.
