### ISSUE TITLE
CI tests to verify RPMs

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1333]
With https://github.com/OSC/ondemand/pull/1329 we can test the RPM builds. Now it's time to test the RPM installation to see that it does what we think it will.

I've had good experience with molecule & ansible for verification tasks, but I'm open to others.

Note that these tests test the RPM installation, so they check system level stuff like file equivalence or if a service is running. Here are a few examples of things we'd test for:
* the right sudoers file got created
* the right crontab got created
* the RPM is actually installed
* httpd (httpd-httpd24) is actually running

**Comment by treydock** [comment]
What I use for Puppet is serverspec: https://serverspec.org/, has rspec like matchers for things on the system. There is also inspec https://github.com/inspec/inspec which I've used for system validation, I think it was born based on what serverspec does but goes much further. What I use for Puppet is beaker which allows for spawning a docker container that has PID 1 as init so things like systemd work and then can copy files in and what not then run puppet catalogs on live system and use serverspec to validate the system state is correct.

**Comment by johrstrom** [comment]
I'll checkout your Puppet CI if you checkout the Ansible CI!

I guess I'd favour ansible because it's super simple to learn.  You know YAML and understand what we're trying to do, so just with those 2 you're already 80% there.

Here's the file to do a very basic verification. It supports systemd in containers too.
https://github.com/OSC/ood-ansible/blob/master/molecule/default/verify.yml

File equivalence is a little wonky though, I have to copy the fixture file into the container and run `diff`, so it's not super clean but seems to work.

**Comment by treydock** [comment]
The Puppet module for openondemand doesn't use a lot of serverspec matchers.  Here are better examples:

https://github.com/treydock/puppet-module-keycloak/blob/master/spec/acceptance/1_class_spec.rb#L14-L21
https://github.com/treydock/puppet-module-keycloak/blob/master/spec/acceptance/1_class_spec.rb#L60-L62

Some additional matchers like using `curl` and checking file contents using expect syntax:
https://github.com/treydock/puppet-module-xdmod/blob/master/spec/acceptance/shared_examples/xdmod.rb

Since both the OOD ansible and puppet code have their own internal validation, I'd think we don't want to mimic that in this repo.  I would prefer the environment bootstrap use commands pulled from OnDemand documentation, so no automation involved to bootstrap the container with RPMs.  I think the only non-standard thing would have to do is instead of using "ondemand-release" RPM to bootstrap repos, would have to setup a testing repo inside container that points to a directory instead of HTTPS endpoint for packages that way can do `yum install ondemand` like we document.  Then run other commands per our docs and then use some tool to validate the state of the system.

I see the big advantage of serverspec is that it uses rspec matchers so more likely people developing OnDemand code will know what they are looking at since there is already a lot of rspec based unit testing in this repo.  While YAML that is simple, what to put into the YAML (keys and values) requires knowledge of something entirely new to this repo, which is also somewhat true for serverspec though much of serverspec syntax is just rspec while the actual matcher itself is the unique thing.  The YAML syntax looks simple enough just has a lot of Ansible-isms involved while most of what you deal with for serverspec is just Ruby and rspec.  For example the bootstrap of a serverspec container using some of the beaker tools doesn't require automation you just do something like this:

```ruby
before(:suite) do
  on hosts, "command to execute here"
  file_contents = <<-EOS
some contents of file here like repo file
EOS
  create_remote_file(hosts, '/path/to/file/in/container', file_contents)
end
```

**Comment by johrstrom** [comment]
Given that we want to get to a place where we:

1. build a package
2. install that package into a container
3. verify that package in that container
4. save that container as an image
5. run browser tests on the image with an array different mounts

Using a Ruby library may benefit us because we'd be able to package it all up into nice neat rake tasks and sort of be more in control.  The transition from 3 -> 5 is really the pain point. We'd want to be able to save the container as an image so that we can then start/stop/restart it in browser end to end tests.  Doing all of that (or some portion) through another library like molecule (python) may be not so nice.

**Comment by treydock** [comment]
So at least with using Ruby based beaker/serverspec, the container is running, the RPMs are installed, so we could perform e2e tests on that running container if we can get the ports exposed like we do for the current e2e tests, no need to package the container up and start a new container.  So the current e2e test code could be used, just rather than pointing at ports from container from current e2e test container, just pointed at ports coming from RPM testing container.

**Comment by johrstrom** [comment]
> we could perform e2e tests on that running container 

We need to save it as an image because we bounce it with new mount points for different use cases.

The pun pre hook tests as an example where we need bounce it to get a new ood-portal.conf that points to a good or bad pre hook.

https://github.com/OSC/ondemand/blob/master/spec/e2e/pun_pre_hook_spec.rb

**Comment by johrstrom** [comment]
Err well, I'm used to running images with `--rm` and stopping _that_ instance and starting a new with (again with `--rm`).

There may be a way to stop and restart a _container_ with new mounts, I'm not entirely sure, but I think using `run --rm` on an image makes more sense for the ephemeral nature of what we're trying to do.

**Comment by treydock** [comment]
I think in those cases rather than stopping/starting containers with new mounts, we just change the contents of relevant files for each test case.  It's trivial with the ruby system testing to write out files so we could just load each fixture, overwrite the config file that fixture is used for, and run the tests again.  

Example:

```ruby
it do
  create_remote_file(hosts, '/opt/hooks/pun_pre_hook', File.read(hook_fixture('good_pre_hook')))
  create_remote_file(hosts, '/etc/ood/config/ood_portal.yml', File.read(portal_fixture('portal_with_prehook.yml')))

  ... run tests or shared example if tests are the same for each use case ...
end
```

The way the beaker/serverspec stuff works is you basically treat the docker container like a full blown VM that runs one copy for the length of all tests. If files need to change for the tests, you modify those files in the running container like if it was an actual VM or provisioned system.  There are no mounts involved because the code has the ability to modify files on the container filesystem.  Under the covers the container SSH port is exposed and files are copied into the container via SCP.

I think one way to re-use some of the logic in those E2E tests is move the actual tests to rspec shared examples and then do like this for RPM container tests and those other tests you linked.  The logic before the tests for things like mounts and container operations stay for those pre_pun_hook tests and the logic before the tests in RPM container tests just modifies files as appropriate.

**Comment by johrstrom** [comment]
OK - the requirement for E2E tests is actually, given some fixture files, bounce apache to get update_ood_portal to run (and bounce the PUN too for good measure).

Seems like we'd be able to handle that through systemd instead of bouncing the container.

So I think it's settled then, breaking out to molecule & ansible is likely too convoluted and having everything in rake tasks that execute serverspec functions seems to be way more intuitive.
