### ISSUE TITLE
Active support dependency in ood-portal-generator?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1347]
It seems like half our runtime dependencies are sorta meaningless.

https://github.com/OSC/ondemand/blob/df8e3ce019202e7a21408cda2da963f339bda216/ood-portal-generator/Gemfile#L7-L8

What core_ext are we using here? Can we just copy the one (Hash) or two (Array) extensions that we're using (with LICENSE and so on)?
https://github.com/OSC/ondemand/blob/df8e3ce019202e7a21408cda2da963f339bda216/ood-portal-generator/lib/ood_portal_generator/dex.rb#L1-L2

You look at our `Gemfile.lock` and we pull in all sorts of gems for features in active support we have no intention of using.

**Comment by treydock** [comment]
So this is not necessarily an issue for at least RPMs because with RPM builds using the `GEM_HOME` so as long as the Rails/ActiveSupport version for like dashboard or other Rails apps matches ood-portal-generator, there is no duplication, the gem files used by ood-portal-generator would be the same as the Rails apps.  I would strongly recommend a similar approach be taken with deb builds to avoid duplication of files and overly large deb files.  I think the only place this could be an issue is if someone is using like `vendor/bundle` type installation directory that is specific to each app.

**Comment by johrstrom** [comment]
> as long as the Rails/ActiveSupport version for like dashboard or other Rails apps matches ood-portal-generator

We're already out of sync. It's an untenable argument to say that we'll be able to keep up or remember to update this dependency, because won't. We already haven't.

https://github.com/OSC/ondemand/blob/df8e3ce019202e7a21408cda2da963f339bda216/apps/dashboard/Gemfile.lock#L16

We need 1-3 files from this library.  Seems like it's a much better solution to just add those 3 mixins than to attempt to manage this.

**Comment by treydock** [comment]
Should we add them to like ood_support or some other ood* gem rather than directly to ood-portal-generator? If we do add them here or to some support gem, I'd advocate for some kind of Rake task to say "download these X files from source Y" where "source Y" is some Github URL that specifies a tag. That way if we do need to perform updates to the files based on upstream changes, that process is at least automated and not going to be something someone does entirely adhoc.

**Comment by johrstrom** [comment]
Yea I'd say just add directly here.
