### ISSUE TITLE
delete a k8s job takes forever

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1348]
I can't tell if this is me or just that I'm working in dev & test, but deleting a kubernetes job takes at least 30 seconds. The upperbound is like 40-50 seconds.

This may be an `ood_core` issue, but there's clearly got to be something we can do to speed this up a bit.

**Comment by treydock** [comment]
I've noticed this too, and as best I can tell the pod itself goes into `Terminating` state but ood_core just waits until the pod no longer is listed in `kubectl get pod`. Maybe one possible change is if the status is `Terminating` just assume the pod is deleted and move on rather than waiting till the pod isn't listed anymore?

**Comment by treydock** [comment]
Actually this is because `kubectl delete pod <id>` waits for the pod to go away entirely.  This needs to be asynchronous command I think.
