### ISSUE TITLE
test crontab file in RPM installation

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1352]
With #1340 we can test RPM installations and we could start by testing the files we inline like the crontab. 

While we test what we write - I'd like to float the idea of changing _how_ we write it.  I'm wondering if we want stuff like this into the `rake install` namespace/task so that other packaging systems can write the same file.

It's a half idea anyhow - the sudoers file would need to be templated for different apache users. What are we trading? consistency for ... simplicity in just writing the HEREDOC in the spec/control/other files?

**Comment by treydock** [comment]
So testing cron actually works won't be possible, because the cron job we deploy is once every 2 hours.  However we can test the contents of deployed cron job.

I think only issue with using a Rake task to install files is we would use the best-practice of using RPM macros:

https://github.com/OSC/ondemand/blob/21c7e270576b034be50c01d245e5a29b47423644/packaging/ondemand.spec#L188

The `%{sysconfdir}` will usually be `/etc` , however I think we could replicate `%{buildroot}` by utilizing something like `DESTDIR`.  I can imagine a Rake task like this:

```
rake install:files[el7] DESTDIR=%{buildroot}
```

The argument would follow pattern used so far to set DIST / distro so that some logic inside the `install` namespace could have a case statement or something to handle `el7` vs `el8` and so on for Debian/Ubuntu too.
