### ISSUE TITLE
update to bundler 2.2

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1383]
If we want ood_core in this repo (which we do) we'll need to update to bundler 2.2 because the vulnerability in bundler is specifically around using local gems and how a malicious gem of a higher version can supersede that local gem. 

Looking here - it's only fixed in RHEL 8. 
https://access.redhat.com/security/cve/CVE-2020-36327

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737384665670) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
We can package our own bundler for RHEL7, we did that during OnDemand 1.8 release before we upgraded to Ruby 2.7 in OnDemand 2.0 where both RHEL7 and RHEL8 had bundler new enough for what we need.  I don't like the idea of maintaining our own bundler but I don't want lack of sufficient versions in RHEL7 to hold us back on things that need to get done.

**Comment by johrstrom** [comment]
It looks like RHEL updated this out from under us,  I just checked test and we're on 2.2. So really, we can go a head and move forward with this without our own packages.

https://access.redhat.com/security/cve/cve-2020-36327

**Comment by treydock** [comment]
Where this can cause problems is the Bundler available on Ubuntu and Debian.  It looks like RedHat bumped it for all flavors we use on RedHat based distros that OnDemand supports.  So for RPMs we won't need to make custom packages but might for Ubuntu and Debian distributions

**Comment by johrstrom** [comment]
Sigh, it is still in `need triaged` phase.

https://ubuntu.com/security/cve-2020-36327

**Comment by johrstrom** [comment]
I wonder if we can't just `gem install bundler` in the packaging script? Or even just add it to the gem file to install with ondemand. I mean if it's in the GEM_PATH, I wonder if Ruby will even care?

**Comment by treydock** [comment]
For OnDemand on RedHat that's fine because we use `ondemand` SCL so no chance `gem install bundler` will overwrite anything installed by RPMs. For Ubuntu and Debian builds, there is the risk a `gem install` will overwrite OS files.  It's very poor practice as sysadmin to allow software that can overwrite OS packaged files or otherwise make it not clear where files are coming from.  If I was to query which package owns a file, shouldn't be possible for that file to possibly be owned by something not in the package manager because someone did `gem install` as root.

**Comment by johrstrom** [comment]
This was fixed at some point. Issuing `find . -name Gemfile.lock | xargs tail -n 3` confirms this for any `Gemfile.lock` that's important.
