### ISSUE TITLE
ood-portal sum fixture files not being tested

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1421]
While working on #1420 I noticed that changes to these fixture files don't break tests. It seems like they should?

```
ood-portal-generator/spec/fixtures/sum.not-default
ood-portal-generator/spec/fixtures/sum.dex
```

Without investigating it, I don't know if it's a bug in the tests or the actual code, but something seems to be off here.  The program should be checking against these checksums, but if they're changed why do the tests still pass?

To replicate, simply modify those files and the tests still pass. The expectation is that they should fail complaining about how the checksums don't match.

**Comment by Oglopf** [comment]
I think this has to do with the actual `update_ood_portal` method. Mocking this locally I noticed that I could change the `sha` value in the `ood_portal.sha256sum` and make a change to the `ood_portal.yml` then update and the configs would update as normal.

But, if you change the actual apache `ood-portal.conf` file, this is when the `sha` will be consulted and the message about a mismatch will occur along with appending `.new` to what files are generated. 

So the test still passes because that's actually the expected behavior as written right now. To check that the `sha` has not changed as well would require a change to the `application.rb` file in the `update_ood_portal` method.

**Comment by johrstrom** [comment]
Oh I think I get it. The checksum probably isn't evaluated.

Here's pseudo code for what I think you may describing.
```ruby
if changed? # tests and your first experiment kick out here
   if right_checksum?
      ...
```

**Comment by johrstrom** [comment]
Seems like it's working as expected.
