### ISSUE TITLE
Shell: Change SSH port

### ISSUE THREAD

**Issue by jeremypmann** [OSC/ondemand#144]
At our University we do not run SSH on port 22. I can't find anything in the shell app that could be a SSH port environment variable. Is this even possible?

**Comment by johrstrom** [comment]
This was taken care of in [this PR](https://github.com/OSC/ondemand/pull/406) and will be released as a part of 1.7.

**Comment by ericfranz** [comment]
The feature in 1.7 will be support for `OOD_SSH_WRAPPER` env var for shell app as replacement of `ssh`. So in this case we could `ssh -p 42` instead of `ssh` and it should work, so I'll mark this as code complete. If you try this after installing 1.7 and you still have problems please reopen this issue or repost another.
