### ISSUE TITLE
JobComposer: If there is only one cluster, hide the cluster dropdown

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#152]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737395296963) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We've seen this asked by the community.  Are you suggesting that instead of a drop down it's just a simple click?  What about the case, like ours, when you have other things in the dropdown (category) like system status.

I'd agree with this in spirit, but we'd have to figure out where to move other items that fit into that 'category' (or change the category).

**Comment by johrstrom** [comment]
Closing this as won't do as we're redoing the job composer and it'll have it's own set of features.
