### ISSUE TITLE
Support Ubuntu 18.04 Focal 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1811]
This ticket is to support Ubuntu 18.04 Focal if possible.  I'm sure there are updates required on the packaging repo.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201766185672540) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
So Ruby is 2.5.1 and nodejs is 8.10.0.  Aren't those going to be too old to work with things in OnDemand?  There would be updates needed to packaging repo to build the necessary buildbox image and also provide necessary ondemand-nginx and ondemand-passenger packages.

**Comment by johrstrom** [comment]
I think we only have a hard requirement for nodejs to be >= 10 right now, so I think we can use the same scheme we do for bionic (20.04) which pulls I want to say 14?

I think as long as we can use bundler 2 with ruby 2.5 we'll be OK with 2.5.  I don't think there's a lot of compatibility issues - sans bundler 1.7 -> 2.x.

**Comment by treydock** [comment]
Bundler with Ubuntu 18.04 is 1.16.1.  I think might be possible to take 20.04 package and make it work for 18.04.  Something I can try.

**Comment by treydock** [comment]
Looks like some of our Gem dependencies require Ruby 2.7:

```
nokogiri-1.13.1-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is
incompatible with the current version, ruby 2.5.1p57
Bundler::InstallError: nokogiri-1.13.1-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is incompatible with the current version, ruby 2.5.1p57
```

**Comment by johrstrom** [comment]
I'm having trouble replicating. Keep getting 403s from rubygems to install.

I don't know if there's a dynamic way to handle that dependency. Hmm...... I guess we'll have to think on it or roll back to `1.12.5`.

**Comment by treydock** [comment]
The error came from here: https://github.com/OSC/ondemand-packaging/runs/5100276242?check_suite_focus=true

This pull request: https://github.com/OSC/ondemand-packaging/pull/188.  That repo builds ondemand packages to validate packaging still works.

Because we keep Gemfile.lock in git it's really hard to be dynamic.  For my Puppet modules which use Ruby, I don't commit Gemfile.lock and instead just set needed versions (or ranges) in Gemfile and then can use Ruby logic to do things like change which Gem version gets pulled in based on Ruby version.

Example:

https://github.com/OSC/puppet-module-openondemand/blob/d8c2d21087145f6784fc70bdc0caae5624d66b25/Gemfile#L24-L25

**Comment by treydock** [comment]
Another approach is different Gemfile and possibly Gemfile.lock and set `BUNDLE_GEMFILE` to different path when needed.

**Comment by johrstrom** [comment]
There's no way 2.1 will hit 18.04 because of the package `ruby-thor` which is version 0.19. This conflicts with versions 1.x which rails needs. If both gems are loaded at the same time there's a runtime error `superclass mismatch for class Command (TypeError)`.  

I cannot seem to get rid of `ruby-thor` unless we force remove it as a preinstall step. I haven't tried that yet, but i can't say how viable an option is if it breaks a system.

The other options would be backporting the packaging updates to release 2.0 and only support 18.04 on that version.  I don't know how much of a lift that would be, especially WRT ubuntu, but it may be our only hope.

**Comment by treydock** [comment]
> I cannot seem to get rid of `ruby-thor` unless we force remove it as a preinstall step. I haven't tried that yet, but i can't say how viable an option is if it breaks a system.

Removing packages with other packages is a non-starter.  The only thing I can think that might work otherwise is something outside OS packages to install Ruby and gems, like rbenv or RVM since Ubuntu doesn't have something like SCL I'm aware of.

> The other options would be backporting the packaging updates to release 2.0 and only support 18.04 on that version. I don't know how much of a lift that would be, especially WRT ubuntu, but it may be our only hope.

That is actually a pretty heavy lift.  Given the issues with supporting 18.04 I'd say we just document that 20.04 is only supported Ubuntu.  Soon we can begin supporting 22.04 possibly as that's next LTS release. I think any sites using 18.04 should have no problem using 20.04 as long as OnDemand is the only thing running on the VM/host.  I've seen more comments in various places like Discourse where sites use dedicated VMs for OnDemand vs sites using a shared system running other roles.

**Comment by johrstrom** [comment]
>  I think any sites using 18.04 should have no problem using 20.04 as long as OnDemand is the only thing running on the VM/host. 

That works for me.

**Comment by johrstrom** [comment]
>  rbenv or RVM 

I may have closed this too quickly. Getting a system installed `rvm` could work, though I thought it wasn't really viable with how we declare dependencies. I mean we have `ruby` as a dependency directly in the control files - so we'd end up having to template them based on the distro version?

I don't know how those toggles would play out and if they'd be easy to add.

**Comment by johrstrom** [comment]
> It's not the most elegant solution but it looks like it could work. 

IDK, it uses native dpkg stages and environment variables, so nothing too crazy. It's nice to have that solution in our back pocket anyhow.

>  But do we really want to go through all that effort, ie have we had requests for Ubuntu 18.04 where upgrading to 20.04 or 22.04 is not an option?

& 

>  Also there are some concerns with installing RVM as root, it's not recommended but haven't tried it in quite some time.

No. I feel like at this point, we understand the landscape such that if someone _needs_ 2.1 they know how to do it and can fork. I suspected rvm wouldn't work at all, but really thinking it through it does seem like a real one off that would only give us trouble in maintaining it.

2.0 can still be built from the source using ansible on Ubuntu 18.  That my just have to be our best effort solution.
