### ISSUE TITLE
JobComposer: Feature request: Open a running job in 'jobstatus' app.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand#189]
If a job is running, show a button that opens up the job status app.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737555199017) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I'm guessing they meant activejobs app, but even so I'm losing this as won't do and/or the features are going to be different in the new job composer.  Specifically in how jobs are visualized I think there is a lot more we could do here, but I do wonder if we should show in in the `projects#show` page instead of redirecting to a different page.
