### ISSUE TITLE
support reading modules from spider output files

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1922]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202019506237690) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Rather than executing `module spider` I wonder if we treat this like we do quotas, where we expect a JSON file to contain this data?  Lmod provides commands to dump all modules into various formats, many of which include JSON output.  I think at OSC we already do this to `/users/reporting/lmod` so there is `/users/reporting/lmod/pitzer.json` for Pitzer.  The command I use via cron running as non-root user (we run as `adm` user):

```
/bin/bash --login -c 'module purge && $LMOD_DIR/spider -o spider-json $MODULEPATH > /users/reporting/lmod/pitzer.json'
```

**Comment by johrstrom** [comment]
Yes, that is it exactly. We're not expecting modules on the webnode, just to be able to read those files.
