### ISSUE TITLE
instructions for installation on ubuntu 20

### ISSUE THREAD

**Issue by pankajd-57** [OSC/ondemand#2180]
hi,

we have login installed with ubuntu 20. We are planning to deploy OOD on the node. Please let me know if this works. If yes, please share the steps to compile and configure.

Thanks

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202686685287535) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
We're about 1-ish weeks away from having a `.deb` file you can install directly on Ubuntu 20.04.  They're available now, but in a nonstandard repository.

So in the interim you can use this nonstandard repository. I _would_ say you could build from the source, but that's likely to be a bit unstable and likely to conflict with a `.deb` file.

Let me know if you want to use the nonstandard repository to deploy immediately - otherwise, I'll update this ticket when we've finally published `2.0.28` for Ubuntu 20.

**Comment by johrstrom** [comment]
Open OnDemand 2.0.28 now supports Ubuntu 20.04. Documentation and automation have both been updated for the same.

Here are the install docs.
https://osc.github.io/ood-documentation/latest/installation/install-software.html

I'm closing this ticket now as we have the packages, automation and documentation for Ubuntu all completed.  Feel free to reopen or open another ticket at any time!
