### ISSUE TITLE
Dashboard: Allow Batch Connect apps to dynamically choose cluster

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand#227]
We want to support an optional dropdown list to choose the cluster to submit to.

![screen 2018-09-12 at 10 58 58 am](https://user-images.githubusercontent.com/512333/45433795-f061b280-b67a-11e8-9427-0e59ba7fb4e1.png)

There are challenges with this:

1. The web form and submission handling assumes its dealing with a single cluster; we will now have to support adding to these config files the config for multiple clusters (default for all, optional per-cluster overrides)
2. The web view would need to update the form dynamically based on the cluster selected
3. The cluster configs provide the ability to "hide" clusters or "invalidate" clusters i.e. if a user doesn't have access to a cluster, so the list of clusters the user can choose (and associated web forms they can see) would need to 
4. The form.yml needs to be able to specify to use all clusters or an array of clusters instead of just 1 cluster. For example instead of `cluster: owens` it might be `cluster: [ owens, ruby ]` or `cluster: *` or even `cluster: foo*` with glob arg (though the last could be dropped if there wasn't a dead simple way to apply those without conflicting with the simple `cluster: owens`).
5. Getting status of running jobs (the cluster submitted to needs to be stored)
6. The deprecated "smart attributes" still in use may need to be addressed, since currently these have adapter specific differences that change based on the cluster.

### Original description:

A suggestion by one of our OOD partners is to allow for the user to choose the cluster to run the app on from a list of clusters.

This will affect:

- app authorization
- smart attributes
- getting status of running jobs

So care must be taken in the redesign to cover these topics

@ericfranz, @basilgohar, @brianmcmichael

**Comment by baverhey** [comment]
Or solution for the Jupyter app
for clusters, reservations, versions per cluster
fomr.yml.erb
`<%
  # This header is not tested
  require 'json'
  clusters = OodAppkit.clusters
  clusters_comma_separated = clusters.map{|c| c.id}.join(",")
  wrapper_command_start = "ood_erb_wrapper --clusters %s " % [clusters_comma_separated]
  all_versions = JSON.parse(`#{wrapper_command_start} --versions IPython`)
  active_reservations = JSON.parse(`#{wrapper_command_start} --reservations`)
  available_clusters = JSON.parse(`#{wrapper_command_start} --has_available IPython`)
%>`

`  cluster:
    label: "Cluster"
    widget: "select"
    options:
      <% available_clusters.each do |c| %>
       - ["<%= c['name'] %>", "<%= c['module'] %>"]
      <% end %>
    value: ""
    required: true

  versions:
    widget: "select"
    options:
      <%= all_versions %>
    label: "Version"
    value: ""
    required: true

  reservation_id:
    widget: "select"
    label: "Reservation id"
    options:
      <%= ["none"] + active_reservations  %>`
`form:
  - bc_num_hours
  - bc_num_slots
  - cluster
  - versions
  - reservation_id
  - sbatch_args
  - bc_email_on_started`

fomr.js
`function reloadVersions() {
	// Find the currently selected cluster
	const cluster_select = document.getElementById('batch_connect_session_context_cluster');
	const selected_cluster = cluster_select.options[cluster_select.selectedIndex].innerHTML;

	// Update the version
	const version_select = document.getElementById('batch_connect_session_context_versions');

	for (let ver of version_select.options) {
		// If the version has not been initialized, initialize it now
		if (!ver.hasAttribute('cluster')) {
			let split = ver.innerHTML.split(';');
			
			// Set the formatted name, cluster and possibly default
			ver.innerHTML = split[0];
			ver.setAttribute('cluster', split[1]);
			if (split[2] === 'default') ver.setAttribute('default_version', true);
		}

		// Hide the irrelevant versions 
		ver.hidden = ver.getAttribute('cluster') !== selected_cluster;
		
		// Select the default version
		ver.selected = ver.hasAttribute('default_version') && !ver.hidden;
	}

	// Update the reservations
	const reservation_select = document.getElementById('batch_connect_session_context_reservation_id');

	for (let res of reservation_select.options) {
		// If the reservation has not been initialized, initialize itnow
		if (!res.hasAttribute('cluster')) {
			let split = res.innerHTML.split(';');

			// Set the formatted name and the cluster
			res.innerHTML = split[0];
			res.setAttribute('cluster', split[1]);
		}

		// Hide the irrelevant versions 
		res.hidden = res.getAttribute('cluster') !== selected_cluster && res.value !== 'none';

		// Select no reservation
		res.selected = res.value === 'none';
	}
}
window.onload = reloadVersions
document.getElementById('batch_connect_session_context_cluster').onchange = reloadVersions
`

**Comment by ericfranz** [comment]
Requirements for a solution for this issue:

1. the admin must be able to specify that an app is for only 1 cluster or a subset of clusters (for example, at OSC perhaps Jupyter is for Owens and Pitzer but MATLAB is only for Owens, and Desktop is for Owens, Pitzer, Ruby, and Quick)
2. an app that is targeting one cluster would not appear in the menu if the user does not have access to that cluster
3. the dropdown to choose a cluster does not include a cluster that the user does not have access to
4. the dropdown to choose a cluster does not include a cluster that you cannot submit jobs to (i.e. job_allow? returns false)
5. the dropdown to choose a cluster does not include a cluster that is invalid (i.e. owns instead of owens)

**Comment by ericfranz** [comment]
>1. the admin must be able to specify that an app is for only 1 cluster or a subset of clusters (for example, at OSC perhaps Jupyter is for Owens and Pitzer but MATLAB is only for Owens, and Desktop is for Owens, Pitzer, Ruby, and Quick)

* Could use a preexisting `cluster: owens` or add `cluster: [owens, pitzer]` or `cluster: *` or omit and let the admin specify a cluster somehow in the web form submission

>2. an app that is targeting one cluster would not appear in the menu if the user does not have access to that cluster

* Could ask admins to use file permissions on the target app to accomplish this. Otherwise if a user tries to submit a job to a cluster the user doesn't have access, a submission error would result.

>3. the dropdown to choose a cluster does not include a cluster that the user does not have access to

* If `cluster: *` or `cluster: owens` or `cluster: [owens, pitzer]` we can filter this list by clusters users have access to; if non we can display an error when the user accesses the app. If admin manually specifies cluster in form, we don't apply this fix.

>4. the dropdown to choose a cluster does not include a cluster that you cannot submit jobs to (i.e. job_allow? returns false)

* Ibid.

>5. the dropdown to choose a cluster does not include a cluster that is invalid (i.e. owns instead of owens)

* Ibid.

>6. properly validate the form submission server side

cluster will be specified to one value, and will have to be valid

>7. In the future version of the launch UI we will want to be able to filter apps by cluster, so knowing this programmatically matters.

* This will be difficult without introducing some concept of "dependencies" to apps, declared in the manifest.yml, especially if every app is consolidated. We can postpone solving this problem now.

>8.  We will also want to be able to define dependencies in the manifest.yml, so that erb rendering of the form.yml.erb can be bypassed when generating the navigation menu, which introduces problems.

* If we do what is suggested above, we can bypass erb rendering, depend only on manifest and not have a problem.

**Comment by johrstrom** [comment]
This was completed in these PRs below and will be released as a part of version 1.8.  They meet all the requirements listed above except for 7 and 8.  Validations are partial given we're allowing free text in some circumstances (like being able to specify cluster in the `submit.yml.erb` or being able to turn the cluster dropdown into a text field in the `form.yml.erb`).  We're only really validating the `cluster` attribute of the `form.yml.erb`, if the cluster is specified in another way, we handle the failure at another layer (likely when it tries to submit the job). 

  [#524](https://github.com/OSC/ondemand/pull/553)
  [#536](https://github.com/OSC/ondemand/pull/536)
  [#538](https://github.com/OSC/ondemand/pull/538)
  [#553](https://github.com/OSC/ondemand/pull/553)
