### ISSUE TITLE
updated packages for Rocky 9

### ISSUE THREAD

**Issue by lesliejelliott** [OSC/ondemand#2456]
you suggest leaving a ticket, I am trying to install this onto a Rocky 9 host

trying to recreate the rpms seems to require circular redundancy 

understand if this is not on the schedule yet :) 
but what harm in asking

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202815755532406/1203649081634993) by [Unito](https://www.unito.io)

**Comment by gerald-byrket** [comment]
Thanks Leslie.  We'll add this to our roadmap.  Not sure when it will happen though.

**Comment by hpc4you** [comment]
On the page, [Rocky 9 installation](https://discourse.openondemand.org/t/rocky-9-installation/2453/4), Jeff Ohrstrom says, 
```
rpm -i https://apt.osc.edu/ondemand/latest/ondemand-release-web-latest-1-7.noarch.rpm
sed /etc/yum.repos.d/ondemand-web.repo -e 's/latest/nightly/g' \
          -e 's/ondemand-web/ondemand-web-nightly/g' > /etc/yum.repos.d/ondemand-nightly-web.repo
```
Then run, 
```
yum module enable ruby:3.0 nodejs:14
yum install ondemand
```

But on Rocky 9.0, it complaints, 

> Error: Problems in request:
> missing groups or modules: ruby:3.0, nodejs:14

If bypass the error message for ruby:3.0 and nodejs:14, 
`yum install ondemand` works fine. 

But after clicking the Login button, a warning message shows up, 
> Web application could not be started by the Phusion Passenger(R) application server.
The web interface does not show up.

**Comment by hpc4you** [comment]
Update. 
Now works. 

OS: Rocky Linux release 9.0 (Blue Onyx)

OOD Version: ondemand-2.1.20230205-137268.d65d799.nightly.el9.x86_64

OOD repo, 
```
[ondemand-web-nightly]
name=Open OnDemand Web Repo
baseurl=https://yum.osc.edu/ondemand/nightly/web/el$releasever/$basearch/
enabled=1
gpgcheck=0
repo_gpgcheck=0
```

`yum install ondemand ondemand-dex` will do all the tricks.

**Comment by treydock** [comment]
There are now RC releases for OnDemand 2.1 that support EL9.  For that `baseurl` replace `nightly` with `latest`.  You may have to uninstall the nightly build in order to install the RC release.

As for the DNF modules, it appears like Rocky Linux has replaced the ruby 3.0 with ruby 3.1 and nodejs 14 with nodejs 18.  This is rather strange considering the purpose of DNF modules is to allow older versions to still exist and people can opt-in to newer versions.  I don't have a RHEL9 system to see if this is also the case.  So far it looks like RHEL9 does still support Ruby 3.0: https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel9_full_life_application_streams.  Looks like NodeJS 16 and 18 are all that are available on RHEL9.  Not sure why Rocky Linux doesn't have the same modules as RedHat, something I'll have to look into just might take some time as we don't have RHEL9 systems deployed yet.

**Comment by treydock** [comment]
So it looks like Rocky 9 doesn't yet support keeping old versions in repos: https://github.com/rocky-linux/peridot/issues/18.  Found that link here: https://wiki.rockylinux.org/rocky/repo/#version-policy.  As a sysadmin that's rather concerning since going from 9.0 to 9.1 you will be forced into some version changes that might be unexpected.  The "vault" repos for Rocky appear to still have Ruby 3.0 and older NodeJS but adding those seems manual since I don't see any Vault repos in `/etc/yum.repos.d/` like CentOS used to do.
