### ISSUE TITLE
recently used widget

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2477]
I went to create a recently used widget today and found it's not exactly easy, so I can't do it for 2.1 but this ticket is to do it at some point.

The widget shows apps that have been recently used (queried from `BatchConnect::Session.cache_root`).  The issue I had was that they're not `preset` apps which they should be. The should be 1 click icons that start a new session based off of the settings from the previous session.

The bit I was having trouble with is actually presetting the app. The way things are now, you can't just do that. At the moment it doesn't recognize these links as preset apps because preset apps are actually sub apps. So somehow we need to build an entirely new sub app on the fly with the settings from the cache file. This is the bit that's difficult, creating a sub app on the fly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792956019905) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
The branch I created in #2478 is the starting point I worked on until I found it increasingly difficult to do.

**Comment by adaybujeda** [comment]
Very interesting. We wanted something similar if not the same. A widget with the most recent executed interactive applications. In the form of quick launchers/pinned apps to re-execute again with the previous parameters.

Instead of re-using preset apps and the pinned apps template, it might be easier to use the `Session.all` and `Session.user_context` and a `button_to` helper setting the `params` attribute to the `user_context` values so that the form is submitted with all the values set. Then style the button to look like a pinned app.

I haven't tried locally, but seems easier this way.

**Comment by adaybujeda** [comment]
This is a functional PR based on the changes you created.
It uses the approach of submitting a form instead of creating a preset app on the fly:
https://github.com/hmdc/ondemand/pull/13

**Comment by johrstrom** [comment]
Looks like exactly what I'd like to see: simplicity and functionality.

**Comment by adaybujeda** [comment]
Great!! I can complete the implementation if you like the approach.

If you give the thumbs up, I will continue working on it

**Comment by johrstrom** [comment]
> Great!! I can complete the implementation if you like the approach.

Yea please, I think it'd have a lot of value and you've got a straightforward solution.

**Comment by adaybujeda** [comment]
I have completed the PR for the final implementation: https://github.com/OSC/ondemand/pull/2503
