### ISSUE TITLE
Run script on login node?

### ISSUE THREAD

**Issue by multimeric** [OSC/ondemand#2790]
I realise this is kind of pushing the intended purpose of OnDemand, but we have some lightweight processes that we want to run on a login node and start via GUI. Integrating with OnDemand would be simpler than making our own GUI for this purpose alone. However it seems that OnDemand always submits to the configured cluster? On the other hand, it is possible to configure the login node: https://osc.github.io/ood-documentation/latest/installation/resource-manager/slurm.html#slurm. So it should be at least technically possible to do this, no?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204504364034976) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
The linux host adapter I believe is what you want. It'll start a process through `tmux` on a node instead of submitting a job to a real scheduler like Slurm.

https://osc.github.io/ood-documentation/latest/installation/resource-manager/linuxhost.html

There's also a `systemd` adapter that uses systemd timers for a similar purpose - it doesn't submit jobs to a batch scheduler only on a given login node. It is undocumented, but available if you can read the source code in here: https://github.com/osc/ood_core

https://osc.github.io/ood-documentation/latest/installation/resource-manager/systemd.html

**Comment by multimeric** [comment]
Oh cool! I think the LinuxHost adapter is exactly what I want. Starting a named session using tmux would fit our use case perfectly. I'll have a look into the docs, many thanks.
