### ISSUE TITLE
project directory created in wrong place

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2822]
I keep getting a numbered directory created in `Rails.root` for some reason. I haven't looked into why or how, but it appears in testing the actual project 2 (shown below in `data/projects/2`) somehow `#{Rails.root}/2` is being created.

![image](https://github.com/OSC/ondemand/assets/4874123/86dca0eb-f068-4459-b6f3-04055a2dc24c)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204621963258995) by [Unito](https://www.unito.io)

**Comment by Oglopf** [comment]
It is happening when scripts#new is hit.
- create a project
- go in and click New Script
- this will create the directory
Also, if you create multiple projects and do this the bug iterates and will create a `1` then `2` etc. in the root.

It does not happen after the initial New Script creation in the project though.

**Comment by Oglopf** [comment]
I think I found it. The `Script::scripts_dir` method looks to be what is causing this to happen. This will fire when the controller `scripst#new` is hit because of this script initializing, but I can't quite see why yet. But this makes sense that if you remove the directory, then do this again, it fires again, because looking at the method:
```ruby
    def scripts_dir(project_dir)
      Pathname.new("#{project_dir}/.ondemand/scripts").tap do |path|
        path.mkpath unless path.exist?
      end
    end
```
It fails the `path.exist?` check.

Now I just need to figure out how to fix it :upside_down_face:
