### ISSUE TITLE
scripts#edit form builder support for static values.

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2948]
The idea here is that you set some form fields to be fixed in `scripts#edit`.  This way, `scripts#show` will either present them with a static field (i.e., it's a hard coded value that's disabled) or not show it at all.

For example, let's say as a user you'd want to 
* set clusters (`clusters`) to `owens` without showing the select drop down menu
* set hours (`bc_num_hours`) to 4 without showing the number field that you can change.

**Comment by abujeda** [comment]
I have been playing around with this issue. The UI for the form builder is getting quite complicated because of the relations between the different options, so I just made the prototype functional.

This is a small demo of the flow I came up with:


![fixed_values](https://github.com/OSC/ondemand/assets/17336210/9137645d-116d-40b4-842e-be3aa01f52e1)
