### ISSUE TITLE
BcDesktop: undefined method to desktop

### ISSUE THREAD

**Issue by jeremypmann** [OSC/ondemand#296]
I am having an issue with bc_desktop and the above error when trying to launch the Interactive Desktop. 

Failed to stage the template with the following error:
undefined method `desktop' for #<BatchConnect::SessionContext:0x00000003cc6098>
* The Shamu Desktop session data for this session can be accessed under the staged root directory.

I have checked the files in the staged root directory and every seems to be correct so I'm not sure what else to look for. My cluster config file is properly formatted, the bc_desktop config file is properly configured as well.

**Comment by johrstrom** [comment]
I hope that you solved your issue from so long ago. For anyone in the future, this happens when you have something in your `submit.yml.erb` that doesn't exist. Things are defined in the `form.yml`.

The takeaway is if you use something called in your submit file then it has to exist in your form.

For posterity here's a similar error message you're seeing. 

![image](https://user-images.githubusercontent.com/4874123/76227359-9309db80-61f5-11ea-8179-183f4f69e652.png)
