### ISSUE TITLE
excludable options are broken for new items.

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3017]
#2902 is already broken.

to replicate
* create a new script
* go to edit that script
* add account fields

**expected behaviour**:
You'd expect to be able to exclude some account fields when clicking 'Remove'.

**actual behaviour**:
Nothing happens when you click remove and you cannot exclude any options.

**Comment by johrstrom** [comment]
And of course the tests for this currently pass, so there's an issue in our test suite too.

**Comment by johrstrom** [comment]
To add insult to injury - when you save, it's not sending the main key. In my case `auto_accounts`.  you can see form this screenshot I'm passing `auto_accounts_exclude` but not `auto_accounts` itself.

![image](https://github.com/OSC/ondemand/assets/4874123/18d47fe9-43f4-44ad-88ce-4ef626fb7428)

**Comment by johrstrom** [comment]
OK - this is 2 bugs.

* the first (the initial report) is that we're not initialing things correctly when the form field is created. (not sure how/why tests succeed with this)
* The second issue is about removing an option that you've currently selected. In the example above - I'm excluding `psz0715`. But `psz0715` is still selected and is in-fact disabled. So the browser (FF in this case) doesn't send it, because i've selected a disabled option.

**Comment by abujeda** [comment]
While looking at these bugs, I found something else:
It seems that Firefox does not respect the HTML options `selected` attribute. When I load the form the first time, the selected option is shown in the select form element. If I change the value and reload the form by pressing the reload button in Firefox, then this new value is shown in the select form element, instead of the option with the attribute selected.

It seems that this is a known issue and the fix is to add autocomplete:'off' to the select element (or maybe the form)
I have tested adding autocomplete off to the select element and it works.

Not sure how important this is.

**Comment by abujeda** [comment]
I think I found another case for bug number 1.
When the dropdown option value is different from the text, like for scripts, Scripts JS will fail because it is trying to match against the text value.

https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/javascript/packs/script_edit.js#L138

This will make `optionToToggle` undefined.

Working on a fix

**Comment by abujeda** [comment]
Possible solution for bug number 2:

<img width="1288" alt="Screenshot 2023-09-15 at 17 24 08" src="https://github.com/OSC/ondemand/assets/17336210/0dc57cfc-0545-40db-bb8d-e765550fb859">

**Comment by johrstrom** [comment]
> Possible solution for bug number 2:

Dynamic Batch connect has logic to handle this - I think we should follow the same

https://github.com/OSC/ondemand/blob/dd1870486e2e9a6cec9a0771afb80eb72152af3b/apps/dashboard/app/javascript/packs/batch_connect.js#L683

**Comment by abujeda** [comment]
For the `batch_connect` solution to work, to select another item automatically. Wouldn't we need to add an empty option to support selecting something when the user removes all the options available?

Or should we not allow the user to remove all and that there should always be at least one item?

**Comment by johrstrom** [comment]
>  Wouldn't we need to add an empty option to support selecting something when the user removes all the options available?

This use case I think could use an alert or not allow it at all. You shouldn't be allowed to remove all items (I thought I had a ticket for the same - but here is a possible duplicate #3050).

There's the semi-related issue on static/fixed values #2948.

**Comment by abujeda** [comment]
Created a PR to fix this issue: https://github.com/OSC/ondemand/pull/3054
