### ISSUE TITLE
Pinned App Images Mis-aligned

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#3368]
A discourse came in pointing out that the images in the pinned apps are not quite displaying correctly.

https://discourse.openondemand.org/t/dashboard-icons-are-misaligned/3282

Only the first image seems to align center as it should, while the remaining images all align left. 

This can be fixed by just adding an `mx-auto` to the `img` tag.

**Comment by abujeda** [comment]
I think this has been fixed already:
https://github.com/OSC/ondemand/pull/3357

**Comment by Oglopf** [comment]
Sadly no, I just recreated it and can see the app images off still plus we had a user report the same problem. So, something is not right it would seem.

**Comment by abujeda** [comment]
That is strange. The fix was specifically for the issue the user is reporting.
I cannot reproduce locally with the latest from master, where the fix is.

Could you confirm what CSS rules are applied, just to check why the fix is not working?
The rule` .app-launcher .app-icon` should be correcting the margin for the pinned_apps

<img width="1284" alt="Screenshot 2024-02-23 at 09 33 29" src="https://github.com/OSC/ondemand/assets/17336210/ef12dd69-70f4-4cc7-9c9a-d5e805a2c284">
