### ISSUE TITLE
Errors in Batch Connect ERB can crash BC::SessionCxt#create

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#357]
Ironically it appears that the crash might be occurring in the error handler. I caused this error by attempting to use `Pathname` methods on a `String`.

![Screen Shot 2019-12-19 at 11 01 06 AM](https://user-images.githubusercontent.com/13316545/71189058-34653f00-2250-11ea-9a9a-1845e8156c55.png)

**Comment by MorganRodgers** [comment]
This occurs when there is a undefined variable used in the ERB. That's the sort of case that we should be able to handle with a more graceful error message.

**Comment by johrstrom** [comment]
I tracked this down to [this line](https://github.com/OSC/ondemand/blob/9386ee2f4a2a368b17d4675be64bcecbec5e6f0a/apps/dashboard/app/helpers/batch_connect/sessions_helper.rb#L178).  I'm not quite sure how it can happen given `key` was a part of the switch statement so it did exist when the case was being evaluated.  And clearly it did hit stage, given that it was trying to create a `_stage` file. 

I suppose we should be more active about making sure we get details on how to reproduce, because obviously it _can_ happen, I just don't know how to get it to happen.

I get the appropriate response when I use undefined methods in my `template/script.sh.erb`. 
![image](https://user-images.githubusercontent.com/4874123/75807181-f22da300-5d52-11ea-8562-0986f381b84a.png)

**Comment by ericfranz** [comment]
https://github.com/OSC/ondemand/pull/429/commits/f1d4a955f9f1f960bf6272cafcc9faeabcb86049 should address this problem by using the ActiveModel::Errors iterator `each` where the second argument is `error`. So if `error` is nil `<%= error %>` should just be empty string instead of crashing.
