### ISSUE TITLE
navbar-toggler doesn't work anymore

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#3580]
After the bootstrap 5 upgrade - the navbar toggler doesn't work anymore. 

The navbar-toggler is this button in the navbar when all the items collapse.

![image](https://github.com/OSC/ondemand/assets/4874123/bc5f506e-c23d-47b2-bd18-bfc27f688b16)

To replicate, simply reduce the width of the page (in this screenshot I'm doing this by expanding my dev tools) and attempt to click the button. Nothing happens when you click it and there are no console logs about what the error could be.

**Comment by ashton22305** [comment]
I'm able to fix this temporarily using dev tools by replacing the `data-target` attribute with `data-bs-target`. Bootstrap 5 changed all `data-*` attributes to `data-bs-*` to avoid conflicts with non-bootstrap code.

Are we using these attributes for anything besides bootstrap? If not, it might be easier to change these all at once instead of whenever we come across an issue it causes.

**Comment by johrstrom** [comment]
> Are we using these attributes for anything besides bootstrap? If not, it might be easier to change these all at once instead of whenever we come across an issue it causes.

It's doubtful that we are. Changing all at once sounds fine to me. We can just look at them all in the review.
