### ISSUE TITLE
Allow users to specify maintance mode file

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#414]
Now that we allow admins to put OOD into maintenance mode we should probably allow them be able to configure what file to serve in case they want to add additional messaging or branding.

**Comment by treydock** [comment]
They can, they just replace `/var/www/ood/public/maintenance/index.html` with their copy:

https://github.com/OSC/ondemand/blob/master/packaging/ondemand.spec#L371

The RPM will not overwrite that file.

**Comment by treydock** [comment]
@johrstrom Is there anything else needed with this? I updated Puppet module to support changing the maintenance index.html: https://github.com/OSC/puppet-module-openondemand/pull/24

**Comment by johrstrom** [comment]
I'm not sure if noreplace is reliable like that? I was able to replicate that it did in fact replace it. Here are the steps.  

I had to downgrade to mimic a new install going forward. I'm not sure if that makes a difference. 

In a centos:7 image
```bash
rpm -ivh https://yum.osc.edu/ondemand/latest/ondemand-release-web-latest-1-6.noarch.rpm
cp /etc/yum.repos.d/ondemand-web.repo /etc/yum.repos.d/ondemand-ci.repo
# add the ci repo s/latest/ci/g and rename the ini 
vi /etc/yum.repos.d/ondemand-ci.repo
yum install -y centos-release-scl
# install 1.7.7_rc5
yum install -y ondemand
# edit the index.html
vi /var/www/ood/public/maintenance/index.html
# downgrade to 1.7.7_rc3
yum downgrade ondemand
yum downgrade ondemand
# update back to rc5
yum update ondemand
```
When it's over you get an .rpmsave file and it's the one that I had modified.
```shell
root@f2dcd711c0e1 /]# diff /var/www/ood/public/maintenance/index.html /var/www/ood/public/maintenance/index.html.rpmsave 
8a9
>     <h2>here's the other thing that I added</h2>
```

**Comment by treydock** [comment]
The issue with your workflow is you downgraded to a version that did NOT include the file after modifying the file, hence the `rpmsave` which is essentially what happens when you uninstall something and `%config` is the reason it became `rpmsave`.  So what you saw is completely expected because you went to a version of the package (via downgrade) that did not include that file, so it had to be uninstalled.

I just tested this workflow on webdev02 with custom index.html:

1. Downgrade to ondemand-1.7.7_rc4
1. File not replaced
1. Upgrade to ondemand-1.7.7_rc5-2
1. File not replaced

In order to test using the versions you used (rc3) you'd have to do this:

```
# downgrade to 1.7.7_rc3
yum downgrade ondemand
yum downgrade ondemand
# edit or install the index.html
# update back to rc5
yum update ondemand
```

Otherwise what you saw is 100% expected and nothing we can do to avoid what you saw, that's just how RPM command treats config files when you downgrade to a version that didn't define that file.

I just tested with webdev02 going from rc3 to rc5 and correctly the file was not replaced.

```
# downgrade to 1.7.7_rc3
yum downgrade ondemand ondemand-selinux
yum downgrade ondemand ondemand-selinux
#  Installing : ondemand-1.7.7_rc3-1.el7.x86_64
# warning: /etc/ood/config/ood_portal.yml created as /etc/ood/config/ood_portal.yml.rpmnew
#   Cleanup    : ondemand-1.7.7_rc4-1.el7.x86_64
# warning: /var/www/ood/public/maintenance/index.html saved as /var/www/ood/public/maintenance/index.html.rpmsave
mv /var/www/ood/public/maintenance/index.html.rpmsave /var/www/ood/public/maintenance/index.html
# update to 1.7.7_rc5-2
yum update ondemand

#   Updating   : ondemand-1.7.7_rc5-2.el7.x86_64
# warning: /etc/ood/config/ood_portal.yml created as /etc/ood/config/ood_portal.yml.rpmnew
# warning: /var/www/ood/public/maintenance/index.html created as /var/www/ood/public/maintenance/index.html.rpmnew
```

Notice the `rpmsave` was after `cleanup` of old package, so what you saw is the removal of a `%config` file because you went from a version with that file defined in spec to a version without the file.  Notice the `rpmnew` when you have the file that exists...this is what will happen when sites deploy a custom `index.html` and we push out a new one, they will get `index.html.rpmnew` which is the correct behavior.

**Comment by johrstrom** [comment]
OK cool! I guess there's nothing to do but document it then.
