### ISSUE TITLE
PUN Web Server needs to be refreshed after some period of inactivity.

### ISSUE THREAD

**Issue by msquee** [OSC/ondemand#454]
_This issue was created based on feedback from the SGCI UX analysis survey_

**Comment by ericfranz** [comment]
Is there more context to this?

**Comment by johrstrom** [comment]
Here's the full quote from the user. The second sentence, I think, is something different that I've never encountered.

```
“PUN Web Server needs to be refreshed after some period of inactivity. Sometimes the New tab is
not opened and I have to try it several times.”
```

Maybe we can make `passenger_pool_idle_time` configurable in `nginx_stage`?  Either way, the statement's kind of always true. It's going to need to be restarted after some time of inactivity, but that's by design, we can't keep these things running forever.

I'd vote close or change to configurable idle time.

**Comment by johrstrom** [comment]
We now allow folks to set `passenger_pool_idle_time`.
