### ISSUE TITLE
MOTD to support ERB

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#505]
We have [this discourse topic](https://discourse.osc.edu/t/how-do-i-display-custom-information-graphics-on-the-dashboard-landing-page/841/11) where a user wants to display some dynamic information in the MOTD. In lieu of a nicer paneling system, I showed him how the markdown formatter can read and display a `.md.erb`.

It may be some time before we can enable really nice dynamic panels, so I thought maybe this is a route we'd want to take. Specifically enabling the markdown formatter to also be able to read and template erb files.

**Comment by ericfranz** [comment]
We would add two new formats: "markdown_erb" and "txt_erb" i.e. `MOTD_FORMAT=markdown_erb` instead of `MOTD_FORMAT=markdown`. 

It would not be based on the file extension because the existing motd format is explicitly specified, and not based on the file extension - because commonly the /etc/motd has no file extension.
