### ISSUE TITLE
Determine whether moving to upstream Passenger + EPEL NGINX is possible

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#731]
1. EPEL NGINX is 1.16.1 rather than 1.17.3 we deploy currently. What is the diff as it relates to OnDemand?
2. Can we use https://www.nginx.com/resources/wiki/modules/upload/?

**Comment by treydock** [comment]
https://www.nginx.com/resources/wiki/modules/upload/ is a third party module: This is the github link from that page: https://github.com/vkholodkov/nginx-upload-module/.  The module does not document a required version of nginx.

**Comment by ericfranz** [comment]
Is it possible to use upstream Passenger + EPEL NGINX with SCL Apache? I don't see why it wouldn't be possible...

But I guess its just a question of whether we use anything in 1.17.3 that is not in 1.16.1.

**Comment by treydock** [comment]
SCL Apache and our use of Passenger + NGINX are totally unrelated.  We don't use mod_passenger so Apache has no effect on Passenger + NGINX.  Also I think NGINX might be provided by OS repos for RHEL8 so no need for EPEL in that case.  That might make deployment harder for us rather than us shipping passenger + nginx that is identical between the OS versions in terms of package naming and such.

**Comment by ericfranz** [comment]
> That might make deployment harder for us rather than us shipping passenger + nginx that is identical between the OS versions in terms of package naming and such.

So do you recommend we not drop EPEL NGINX and our custom Passenger rpm?

**Comment by treydock** [comment]
We don't use EPEL NGINX, we have custom Passenger RPM that also is responsible for building NGINX so we provides RPMs for both NGINX (`ondemand-nginx`) and Passenger (`ondemand-passenger`).  The recent releases of Passenger stopped building their own NGINX and instead they rely on EPEL or OS NGINX so if we went with upstream Passenger we'd have to use EPEL or OS NGINX.

I don't see much advantage in using upstream Passenger and EPEL/OS NGINX other than one less thing for us to maintain.  It will complicate install docs on our end as right now we provide both `ondemand-nginx` and `ondemand-passenger` which is the same for both EL7 and EL8, but if we go with upstream approach the method for getting NGINX will vary between OSes.  Also it will require us to provide docs for people to enable both Passenger RPM repo and EPEL repo.  Right now we have no direct dependencies on EPEL or any repos aside from SCL and OS repos.

I also have concerns with how to ensure that sites actually using NGINX from EPEL/OS don't break OnDemand's usage with their configs if we began relying on EPEL/OS NGINX.  The way we package NGINX it's essentially an appliance for OnDemand so we know with a high degree of certainty it will behave the same for everyone because it's only configured for OnDemand.

**Comment by treydock** [comment]
Just checked and looks like EL8 OS provides even older than EPEL, looks like it's 1.14.1.  If you want newer you have to enable the necessary DNF modules which I'm not 100% sure how we'd interact with the 1.18 module they provide.  I know how to enable a module and install it but no experience using software that comes from a module.

**Comment by ericfranz** [comment]
I'll close as not doing for now.
