### ISSUE TITLE
how does the Ruby 2.7 upgrade affect apps

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#784]
We need to do a little investigation into how the upgrade to ruby 2.7 affects apps. Specifically whether the _need_ to upgrade or if they have a clean way to continue to use ruby 2.5 with 2.5 gems (wherever they may be).

Off the top I'd think the cases are:
* Apps that have 2.5 gems in their own `vendor/bundle`
* Apps that use 2.5 gems from ondemand-gems RPM
* Apps that use bundler 1.7.x.

**Comment by treydock** [comment]
We have to upgrade to avoid EOL Ruby 2.5 SCL in a few months.  Also the way `ondemand-runtime` sets of GEM_PATH the Ruby version is in path so once the new runtime is present the gems from ondemand-gems RPM from previous version won't be accessible.

Apps only used bundler 1.17.x because we forced them to via ondemand-rubygem-bundler RPM because we need newer bundler than what shipped with Ruby 2.5 SCL.

Given this is all happening on a major version bump, I think we just have to keep things simple, any apps from OnDemand 1.x that wish to run with 2.0 have to be rebuilt.  Doing anything to maintain compatibility would just introduce a lot of extra complexity and would also not be possible with RHEL 8 because on RHEL 8 you can not have both Ruby 2.5 and Ruby 2.7 installed at the same time and I don't think we should try to maintain some kind of backwards compatibility for only one supported OS when that compatibility isn't possible with newer OSes.

**Comment by johrstrom** [comment]
Yep. 1.8 apps would need to be rebuilt or hack a `bin/ruby` to continue to use their setup.
