### ISSUE TITLE
Review OnDemand code for places where we make assumption that a group name will not have any spaces

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#786]
Evidently in certain cases group names could have spaces (thus the reason for https://github.com/OSC/nginx_stage/pull/45). While that PR fixed it in nginx_stage it is possible we make similar assumptions in other locations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737645991189) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I think we may have gotten this by accident when I did `CurrentUser#groups` which pulls from Etc instead of parsing `id` output like `ood_support`.  Though I'll now file a ticket upstream with `ood_support` for the same.


https://github.com/OSC/ondemand/blob/dda7c0dd579765c5f983874f6f139f083804f883/apps/dashboard/app/models/current_user.rb#L42-L50
