### ISSUE TITLE
"Unable to contact settings server" when lauching XFCE remote desktop session on CentOS8

### ISSUE THREAD

**Issue by guimaluf** [OSC/ondemand#872]
I've configured a CentOS8 compute node using the `ondemand-compute` and `@xfce` packages.

When launching the remote desktop interactive app job I'd get
![image (1)](https://user-images.githubusercontent.com/3178490/106655305-144a2980-6591-11eb-9d8f-6344dc2b3c35.png)

Weirdly I was able to ssh to the compute node and run `DISPLAY=:1 xfce4-session`, the session would then start over the previous error message
![image (2)](https://user-images.githubusercontent.com/3178490/106655837-cb46a500-6591-11eb-8b1c-cbc294b0f547.png)

Looking #700 and https://bbs.archlinux.org/viewtopic.php?id=216491 

I end up discovering that `dbus-launch xfce4-session` fix the issue.
Anyhow, I'm reporting here to see what could be done instead to make it work without having to touch the `bc_desktop/template/desktops/xfce.sh` script.l

**Comment by johrstrom** [comment]
You can override the `before_script` and set the PATH there.

Here's how we do it to force the XDG_RUNTIME_DIR for OSC systems.

https://github.com/OSC/osc-ood-config/blob/89b171a48aafc6a017fe952bd5fbfaf558d3284b/ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb#L54-L61

**Comment by orbsmiv** [comment]
I've been experiencing a similar dbus-related issue on CentOS / RHEL 8 with OOD apps that require `xfwm4`, `xfsettingsd` etc. My workaround is to include the following in the `script.sh.erb` file:
```
eval $(dbus-launch --sh-syntax)
```

**Comment by johrstrom** [comment]
@orbsmiv That works perfectly! I'd adding that change to the distribution.  I now realize that modifying the PATH could actually be bad or wrong for the user as now they're path is modified. But you can add `eval $(dbus-launch --sh-syntax)` to the `before_script` section so that you don't have to modify the actual script.  Of course when the actual fix gets pushed out you'd have to change it, so it may be preferable to edit the source file, and when it gets updated by the new release you won't have to worry about updates - it'll just continue to work.

Just for the future: pull requests are always welcome! So if you have a fix, feel free to open a pull request with it! We'd love to see more community contributions.

**Comment by johrstrom** [comment]
This was fixed in #942 and being released in the `2.0.x` release.  If there are more questions on the issue feel free to reopen this ticket or open another!
