### ISSUE TITLE
Replace Install Location column in all apps with a shorter text description to right of the app name

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#907]
The Install Location is very prominent, takes up a lot of space, and probably doesn't matter much to users, at least not as much as the other columns. Instead, this information can be included in text that follows the name of the app (But perhaps not part of the link).

- If it is a "sys" app, don't append anything extra
- If it is a user shared app can have a string similar to what we do on apps.awesim.org: _- Shared by Eric Franz (efranz)_ in muted text following the name (or underneath the name
- If it is a dev app, just - _development_

**Comment by johrstrom** [comment]
I thought about just re-using OodApp#caption. Are you OK with `pull-right` for both dev/sys captions or do you want it underneath the link? I opted to pull right so that all the rows are the same height.

![image](https://user-images.githubusercontent.com/4874123/110173948-60290200-7dcd-11eb-8342-7001b52ebf4b.png)
