### ISSUE TITLE
Pinned apps crashes dashboard if no pinned apps found by filter

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#951]

**Comment by johrstrom** [comment]
I can't replicate when I tried a few different configs. Can you share the config you used?

**Comment by johrstrom** [comment]
I can replicate by setting `NavConfig.categories = []` (or similar, basically just removing 'Apps' from the list.

So `@featured_group` - what's passed into the partial - gets filtered and is nil when `@pinned_apps` is still valid and will be shown on the landing page. So the crash is due to calling `group.title` in the partial when `group` (an item in @featured_group which is nil) is nil.
